<?php

namespace App\Services\Dashboard;

class DashboardService
{
    // GRAFIK FLOW BERAT BARANG MASUK DAN KELUAR PERHARINYA
    // GRAFIK FLOW BARANG YANG DI KIRIM KE DMK PERHARINYA
    // GRAFIK FLOW BARANG YANG DI KIRIM KE JASA CUCI / NAMA JASA CUCI 
    // GRAFIK BARANG MASUK PER SUPLIER
    // GRAFIK TOTAL BARANG YANG DI GRADING PERHARI , BISA DI LIAT DARI DATA INPUTAN GRADING PERHARINYA
}
